openapi: 3.0.0

info:
  title: Narmesteleder API
  description: API for narmesteleder.
  version: 1.0.0
servers:
  - url: 'https://narmesteleder.dev.nav.no'
paths:
  /arbeidsgiver/forskutterer:
    get:
      summary: returnerer hvorvidt arbeidsgiver forskutterer for angitt orgnummer og fnr
      operationId: arbeidsgiverForskutterer
      tags:
        - Forskuttering
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/Orgnummer'
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          $ref: '#/components/responses/ForskutteringRespons'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /leder/narmesteleder/aktive:
    get:
      summary: returnerer liste av alle aktive NL-koblinger for angitt leder-fnr
      operationId: getNarmestelederRelasjonerForLeder
      tags:
        - Narmesteleder-leder for serviceuser (AzureAD)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/NarmesteLederFnr'
      responses:
        '200':
          $ref: '#/components/responses/NarmesteLederRelasjonListeResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /sykmeldt/narmesteleder:
    get:
      summary: returnerer aktiv nærmeste leder for angitt fnr og orgnummer
      operationId: getNarmestelederForSykmeldt
      tags:
        - Narmesteleder-sykmeldt for serviceuser (AzureAD)
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/Orgnummer'
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          $ref: '#/components/responses/NarmesteLederRelasjonResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /sykmeldt/narmesteledere:
    get:
      summary: returnerer alle nærmeste leder-relasjoner for angitt fnr
      operationId: getNarmestelederForSykmeldt
      tags:
        - Narmesteleder-sykmeldt for serviceuser (AzureAD)
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/Utvidet'
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          $ref: '#/components/responses/NarmesteLederRelasjonListeResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /{orgnummer}/avkreft:
    post:
      summary: avkrefter evt aktiv leder-relasjon for angitt orgnummer for sykmeldt-fnr for fnr i access_token
      operationId: avkreftNarmestelederForSykmeldt
      tags:
        - Narmesteleder sykmeldt api
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/OrgnummerPath'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /user/sykmeldt/narmesteledere:
    get:
      summary: henter nærmeste ledere for fnr i access_token
      operationId: getNarmestelederForSykmeldtUser
      tags:
        - Narmesteleder sykmeldt api
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          $ref: '#/components/responses/NarmesteLederListeResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /syforest/narmesteledere:
    get:
      summary: henter nærmeste ledere for fnr i access_token på syforest-format
      operationId: getNarmestelederForSykmeldtUserSyforest
      tags:
        - Narmesteleder sykmeldt api
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          $ref: '#/components/responses/SyforestNarmesteLederListeResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /arbeidsgiver/{orgnummer}/avkreft:
    post:
      summary: avkrefter aktiv leder-relasjon for angitt orgnummer og sykmeldt-fnr for leder-fnr i access_token
      operationId: avkreftNarmestelederForSykmeldtFraLeder
      tags:
        - Narmesteleder arbeidsgiver api
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/OrgnummerPath'
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /arbeidsgiver/ansatte:
    get:
      summary: henter alle ansatte til narmesteleder, leder-fnr i access_token
      operationId: getArbeidsgiverAnsatte
      tags:
        - Narmesteleder arbeidsgiver api
      security:
        - bearerAuth: [ ]
      parameters:
        - in: query
          name: status
          schema:
            default: ALL
            type: string
            enum: [ALL, ACTIVE, INACTIVE]
      responses:
        '200':
          $ref: '#/components/responses/AnsatteResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /arbeidsgiver/ansatt/{narmestelederId}:
    get:
      summary: henter en narmesteleder kobling for narmestelederId og leder-fnr i access_token
      operationId: getArbeidsgiverAnsatt
      tags:
        - Narmesteleder arbeidsgiver api
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          $ref: '#/components/responses/AnsattResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

components:
  responses:
    ForskutteringRespons:
      description: "Forskuttering response"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Forskuttering'
    NarmesteLederRelasjonListeResponse:
      description: "NarmesteLederRelasjon response"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NarmesteLederRelasjon'
    NarmesteLederRelasjonResponse:
      description: "Arbeidsforhold response"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NarmesteLederRelasjon'
    NarmesteLederListeResponse:
      description: "NarmesteLeder response"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/NarmesteLeder'
    SyforestNarmesteLederListeResponse:
      description: "SyforestNarmesteLeder response"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SyforestNarmesteLeder'
    AnsatteResponse:
      description: "Ansatte response"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ansatte'
    AnsattResponse:
      description: "Ansatt response"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ansatt'

  parameters:
    Orgnummer:
      description: Bedriftens orgnummer
      name: orgnummer
      in: query
      required: true
      schema:
        type: string
      example: '974600951'
    SykmeldtFnr:
      description: fnr for den sykmeldte
      name: Sykmeldt-Fnr
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/Fodselsnummer'
    NarmesteLederFnr:
      description: fnr for nærmeste leder
      name: Narmeste-Leder-Fnr
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/Fodselsnummer'
    Utvidet:
      description: ja eller nei for om navn på leder skal inkluderes i responsen
      name: utvidet
      in: query
      required: false
      schema:
        type: string
      example: 'ja'
    OrgnummerPath:
        description: Bedriftens orgnummer
        name: orgnummer
        in: path
        required: true
        schema:
          type: string
        example: '974600951'
  schemas:
    Date:
      type: string
      format: date
    Timestamp:
      type: string
      format: 'date-time'
    Fodselsnummer:
      type: string
      minLength: 11
      maxLength: 11
      example: '01234567891'
    Tilgang:
      type: string
      enum: [SYKMELDING, SYKEPENGESOKNAD, MOTE, OPPFOLGINGSPLAN]
    NarmesteLederRelasjon:
      type: object
      required:
        - fnr
        - orgnummer
        - narmesteLederFnr
        - narmesteLederTelefonnummer
        - narmesteLederEpost
        - aktivFom
        - skrivetilgang
        - tilganger
        - timestamp
      properties:
        fnr:
          $ref: '#/components/schemas/Fodselsnummer'
        orgnummer:
          type: string
        narmesteLederFnr:
          $ref: '#/components/schemas/Fodselsnummer'
        narmesteLederTelefonnummer:
          type: string
        narmesteLederEpost:
          type: string
        aktivFom:
          $ref: '#/components/schemas/Date'
        aktivTom:
          $ref: '#/components/schemas/Date'
        arbeidsgiverForskutterer:
          type: boolean
        skrivetilgang:
          type: boolean
        tilganger:
          type: array
          items:
            $ref: '#/components/schemas/Tilgang'
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        navn:
          type: string
    NarmesteLeder:
      type: object
      required:
        - orgnummer
        - narmesteLederTelefonnummer
        - narmesteLederEpost
        - aktivFom
        - timestamp
      properties:
        orgnummer:
          type: string
        narmesteLederTelefonnummer:
          type: string
        narmesteLederEpost:
          type: string
        aktivFom:
          $ref: '#/components/schemas/Date'
        aktivTom:
          $ref: '#/components/schemas/Date'
        arbeidsgiverForskutterer:
          type: boolean
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        navn:
          type: string
    Ansatte:
      type: object
      properties:
        ansatte:
          type: array
          items:
            $ref: '#/components/schemas/Ansatt'
    Ansatt:
      type: object
      properties:
        fnr:
          type: string
          description: FNR til den ansatte
        navn:
          type: string
          description: Navn til den ansatte
        orgnummer:
          type: string
          description: organisasjonsnr
        narmestelederId:
          type: string
          description: ID på denne koblingen mellom ansatt og leder

    SyforestNarmesteLeder:
      type: object
      required:
        - aktoerId
        - navn
        - epost
        - mobil
        - orgnummer
        - organisasjonsnavn
      properties:
        aktoerId:
          type: string
        navn:
          type: string
        epost:
          type: string
        mobil:
          type: string
        orgnummer:
          type: string
        organisasjonsnavn:
          type: string
        aktivTom:
          $ref: '#/components/schemas/Date'
        arbeidsgiverForskuttererLoenn:
          type: boolean

    Forskuttering:
      type: string
      enum: [JA,
             NEI,
             UKJENT]

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
