apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2560m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  vault:
    enabled: false
  envFrom:
    - secret: narmesteleder-secret
    - secret: narmesteleder-redis-password
    - configmap: loginservice-idporten
  ingresses:
    - "https://narmesteleder.intern.nav.no"
    - "https://narmesteleder.nav.no"
  webproxy: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfosoknad
          namespace: flex
          cluster: prod-fss
        - application: syfovarsel
          namespace: flex
          cluster: prod-fss
        - application: syfobrukertilgang
          namespace: default
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: default
          cluster: prod-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: modiasyforest
          namespace: default
          cluster: prod-fss
        - application: syfosmaltinn
        - application: sykmeldinger-arbeidsgiver
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: prod-fss
        - application: notifikasjon-bruker-api
          namespace: fager
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      rules:
        - application: narmesteleder-redis
      external:
        - host: https://pdl-api.prod-fss-pub.nais.io
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: https://api-gw.oera.no/security-token-service/rest/v1/sts/token
    - name: PDL_GRAPHQL_PATH
      value: https://api-gw.oera.no/pdl-api/graphql
    - name: KAFKA_CLIENT_ID
      value: narmesteleder
    - name: REGISTER_BASE_PATH
      value: https://api-gw.oera.no
    - name: ALLOWED_ORIGIN
      value: tjenester.nav.no,www.nav.no
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default