apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: true
        insights:
          enabled: true
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 450Mi
  vault:
    enabled: false
  envFrom:
    - secret: narmesteleder-secret
    - secret: narmesteleder-redis-password
    - configmap: loginservice-idporten
  ingresses:
    - "https://narmesteleder.dev.nav.no"
    - "https://narmesteleder.dev.intern.nav.no"
  webproxy: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: dev-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfomoteadmin
          namespace: default
          cluster: dev-fss
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfosmaltinn
        - application: narmesteleder
        - application: sykmeldinger-arbeidsgiver
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: dev-fss
        - application: sykmeldinger-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: debug-dings
          namespace: plattformsikkerhet
        - application: notifikasjon-bruker-api
          namespace: fager
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfoservice-data-syfosmregister
          namespace: teamsykmelding
          cluster: dev-fss
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-fss
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
    outbound:
      rules:
        - application: narmesteleder-redis
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: aareg-services-q1.dev-fss-pub.nais.io
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: KAFKA_CLIENT_ID
      value: narmesteleder
    - name: AAREG_URL
      value: https://aareg-services-q1.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
    - name: ALLOWED_ORIGIN
      value: tjenester-q1.nav.no,www-gcp.dev.nav.no,narmesteleder.dev.nav.no
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
