apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 3
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2560m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  vault:
    enabled: false
  envFrom:
    - secret: narmesteleder-secret
    - configmap: loginservice-idporten
  ingresses:
    - "https://narmesteleder.intern.nav.no"
    - "https://narmesteleder.nav.no"
  webproxy: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfoarbeidsgivertilgang
          namespace: default
          cluster: prod-fss
        - application: syfosoknad
          namespace: flex
          cluster: prod-fss
        - application: syfovarsel
          namespace: default
          cluster: prod-fss
        - application: syfobrukertilgang
          namespace: default
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: default
          cluster: prod-fss
        - application: syfooppfolgingsplanservice
          namespace: default
          cluster: prod-fss
        - application: modiasyforest
          namespace: default
          cluster: prod-fss
        - application: syfosmaltinn
        - application: sykmeldinger-backend
          namespace: default
          cluster: prod-fss
    outbound:
      external:
        - host: syfonarmesteleder.prod-fss-pub.nais.io
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: https://api-gw.oera.no/security-token-service/rest/v1/sts/token
    - name: PDL_GRAPHQL_PATH
      value: https://api-gw.oera.no/pdl-api/graphql
    - name: KAFKA_CLIENT_ID
      value: narmesteleder
    - name: REGISTER_BASE_PATH
      value: https://api-gw.oera.no
    - name: AAD_ACCESS_TOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: SYFONARMESTELEDER_CLIENT_ID
      value: ccf8c36f-27e6-4e76-8250-9a49939df7ef
    - name: SYFONARMESTELEDER_URL
      value: https://syfonarmesteleder.prod-fss-pub.nais.io
    - name: ALLOWED_ORIGIN
      value: tjenester.nav.no
